Update paylink
paynl/magento2-plugin pull request #107
Opened 2020-12-08 08:15 UTC by kevinverschoor

2020-12-16 14:18 UTC, bryantvandenberg approved these changes

2021-01-05 15:57 UTC, bryantvandenberg approved these changes

2021-01-08 08:56 UTC, woutse commented on etc/adminhtml/paymentmethods/paylink.xml
> +            <source_model>Paynl\Payment\Model\Config\Source\SendNewOrderEmail</source_model>
Mistake?

2021-01-16 16:24 UTC, woutse requested changes
See mail

2021-01-18 21:41 UTC, woutse approved these changes

2021-01-18 21:41 UTC, merged