Add option to show or hide specific paymentmethodes for companies/pri…
paynl/magento2-plugin pull request #82
Opened 2020-08-13 09:34 UTC by kevinverschoor

…vate customers.

2020-08-19 12:50 UTC, annevelden approved these changes

2020-08-20 09:20 UTC, woutse commented on Model/ConfigProvider.php
> +    public function getMethodCodes()
Dit lijkt niet gebruikt te worden

2020-08-20 09:26 UTC, woutse commented on Model/ConfigProvider.php
> +        $url = $this->paynlConfig->getIconUrl($code);
klopt dit?

2020-08-20 09:35 UTC, woutse commented on Model/Paymentmethod/PaymentMethod.php
> +        $objectManager =  '\Magento\Framework\App\ObjectManager'::getInstance();
kloppen de quotes?

2020-08-20 09:38 UTC, woutse commented on Model/Paymentmethod/PaymentMethod.php
> +        Transaction::refund($transactionId, $amount);
dit lijkt me niet de bedoeling.

2020-08-20 09:47 UTC, woutse requested changes
Zie comments

2020-09-11 13:57 UTC, woutse approved these changes

2020-09-14 17:49 UTC, annevelden approved these changes

2020-09-14 21:41 UTC, merged