Add option to hide payment methode based on shippingmethode
paynl/magento2-plugin pull request #96
Opened 2020-10-28 22:18 UTC by kevinverschoor

2020-10-29 09:02 UTC, woutse requested changes
See comments

2020-11-02 13:08 UTC, bryantvandenberg approved these changes

2020-11-02 20:06 UTC, woutse requested changes
Zie Teams comments

2020-11-10 11:22 UTC, bryantvandenberg approved these changes

2020-11-10 12:04 UTC, woutse approved these changes

2020-11-10 12:04 UTC, merged